fix(aws/loadbalancing): Mark draining instances as out of service
spinnaker/clouddriver pull request #5060
Opened 2020-10-30 12:12 UTC by programminh

Marking draining instances as "UP" would falsely finish a pipeline successfully.

More details about this bug is documented here: https://github.com/spinnaker/spinnaker/issues/5867
As well as a slack conversation here https://spinnakerteam.slack.com/archives/CB78MFQPP/p1588774672064600

2020-11-05 19:42 UTC, cfieber commented
There are tradeoffs either direction we take with this as it stands but I think you have to go more out of your way to shoot yourself in the foot with the current implementation than with the proposed change

Definitely interested in @dreynaud opinion here though

2020-11-05 23:54 UTC, dreynaud commented
With the current `draining == Up` model, we have the problem that unhealthy/dying instances are considered up (by orca tasks), potentially leading to an incident where we would end up with no instances in service.

With this change (`draining == OutOfService`), we have the problem that they would pass a waitForDown check in orca. So I guess the worst case here is that we might terminate `draining` instances, causing errors for the clients that are still on the line and maybe data loss.

My take is that `draining` instances should:
- NOT pass an up check (i.e. they should not be considered part of the normal rotation)
- but also NOT pass a down check (i.e. they are not taking new traffic but they are maybe still doing stuff)

My recommendation would be to introduce a new `HealthState` constant, like `Draining`, or `Stopping` to be a bit more vendor agnostic.

2020-11-05 23:59 UTC, dreynaud requested changes
See https://github.com/spinnaker/clouddriver/pull/5060#issuecomment-722712064, I believe it would be better to return something like `HealthState.Stopping`

2020-11-06 17:19 UTC, dreynaud commented
Thanks for the change, LGTM! 👍

2020-11-06 17:19 UTC, merged

2020-11-16 09:20 UTC, gardleopard commented
Thank you!