feat: Add the possibility to update the default handler for the Global Resource Property Registry.
spinnaker/clouddriver pull request #5963
Opened 2023-06-09 15:52 UTC by armory-abedonik

Unfortunately, it is not possible to override the default handler behavior from a Spinnaker plugin code. Therefore, we have decided to introduce a new setter function specifically designed to address this requirement.

2023-06-09 19:08 UTC, sergio-quintero approved these changes

2023-06-12 20:41 UTC, armory-abedonik commented
Hi @dbyron-sf, please take a look at this pull request. Thank you in advance!

2023-06-13 06:21 UTC, ovidiupopa07 requested changes

2023-06-13 06:21 UTC, ovidiupopa07 commented on clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/GlobalResourcePropertyRegistry.java
> +  public void setDefaultHandler(KubernetesUnregisteredCustomResourceHandler defaultHandler) {
Would it make sense to check if the 'defaultHandler' is not null before creating the default properties?

2023-06-13 06:53 UTC, ovidiupopa07 approved these changes

2023-06-13 10:10 UTC, sw-abedonik commented
@mergifyio refresh

2023-06-13 10:11 UTC, ovidiupopa07 commented
@mergifyio refresh

2023-06-13 15:51 UTC, dbyron-sf approved these changes

2023-06-14 09:18 UTC, merged

2023-06-14 09:20 UTC, ovidiupopa07 commented
Because mergify doesn't have permission to update the repository, we manually merged the PR.

2023-06-14 17:56 UTC, sw-abedonik commented
Hi @dbyron-sf, please push a new git tag based on the master branch for this repo. Thank you in advance!

2023-06-14 18:01 UTC, dbyron-sf commented
Can you work with someone from Armory to take care of this please?

2024-12-19 05:18 UTC, edgarulg commented
@Mergify backport release-1.31.x